### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by deviratechllc** [75nineteen/order-simulator-woocommerce#6]
Just curious if this plugin is still working on the latest version of WooCommerce? I installed and setup successfully but it seems to only want to create one order every time it runs on the hour. Any suggestions? Thanks in advance.

**Comment by theritesite** [comment]
Yes, it still works. I have a test site with it running 4 orders every hour for general testing. There was an issue where it wasnt querying correctly for customer users, which forced "guest" checkout for nearly everyone for me. My thought: you might have guest checkout disabled, coupled with that error, causing the orders to never get to the creation point?

**Comment by deviratechllc** [comment]
I was actually able to narrow down the issue to be related to the host. For some reason (possibly something to do with rate limiting?) the plugin does not work if your WooCommerce store is hosted on wpengine. Moved store to a different host and the plugin worked just fine. Thanks again!
